#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -z "$(git diff --cached --ignore-blank-lines --unified=0 | grep -E '^[+-]\s' | grep -vE '^[+-]\s*$')" ]; then
  echo "Error: commit must contain new content. Please add new translations or changes."
  exit 1
else
  exit 0
fi

npm test
